FROM python:3.6.3

WORKDIR /home

# AWS KEYS
ENV AWS_ACCES_KEY_ID=AKIAJQND64KSHJ265EMA 
ENV AWS_SECRET_ACCES_KEY=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
ENV BUCKET_NAME=course-election-repository

# DEPENDENCIES
RUN pip install boto3
