# Run it using: $ docker-compose up

version: "3"

services:

  flask_api:
    restart: always
    build: ./backend/flask_api/
    networks:
      - ADS4_network
    ports:
      - 3031:3031
    volumes:
      - ./backend/flask_api:/usr/src/site
    command: uwsgi --emperor /usr/src/site

  nginx_frontend:
    restart: always
    image: nginx:latest
    networks:
      - ADS4_network
    volumes:
      - ./view/:/www/static
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80
    depends_on:
      - flask_api

  mongodb:
    restart: always
    image: mongo
    networks:
      - ADS4_network
    volumes:
      - ./backend/mongodb:/data/db
    ports:
      - 27017:27017

networks:
  ADS4_network:
    driver: bridge
